In [91]:
from sklearn.datasets import make_regression
import matplotlib.pyplot as plt
import numpy as np

In [92]:
x,y=make_regression(n_samples=100,n_features=1,n_informative=1,n_targets=1,noise=20,random_state=13)

In [93]:
y

array([-3.43198806e+01, -9.42120961e+00, -1.90881877e+01,  2.04372122e+01,
        2.77559659e+01, -2.90750046e+00, -1.41987828e+01,  5.40025891e+00,
       -2.64264302e+01, -3.49067872e+01,  3.73362043e+01,  1.28532816e+01,
        2.50289888e+01, -1.89608736e+01, -2.34655852e+01,  3.77839324e+01,
        6.69670792e+00, -5.57201352e+00, -4.92158778e+01,  1.59474399e+01,
       -4.29667324e+01,  6.09015466e+00, -2.53194769e+01,  6.28216706e+01,
        1.24870400e+01, -3.27136530e+01, -1.88255476e+01, -2.93912926e+01,
       -2.86886731e+01,  4.38924069e+00,  4.63542396e+01,  2.43919519e+01,
        3.79848517e+01, -3.45767718e+01, -6.18736296e+01, -4.64421597e+01,
       -6.88808416e+00,  3.96988084e+01, -3.52373298e+01,  8.36850884e+00,
       -3.96814412e+01,  8.27318308e+00, -4.40722161e+00, -3.01350607e+00,
        5.78213629e+01,  2.46525603e+01,  1.81131707e+01, -5.22849035e+01,
        3.59187182e+01,  1.58411788e+01,  2.40080546e+01, -2.51245994e+01,
       -4.39284313e+01,  

In [94]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [95]:
x_train

array([[ 1.3501879 ],
       [-0.53032741],
       [-0.33861825],
       [-0.27813452],
       [-0.14521133],
       [ 0.45315861],
       [-1.51284512],
       [ 1.84961257],
       [-0.42989708],
       [ 0.71097479],
       [ 0.39724133],
       [-0.6209797 ],
       [-0.98027432],
       [-0.48137142],
       [-0.38445769],
       [ 0.86121137],
       [-0.76403397],
       [-1.92415945],
       [-1.18541881],
       [ 0.63988397],
       [ 1.13833305],
       [-2.18711527],
       [ 0.18494595],
       [-0.31485808],
       [-0.32212366],
       [ 1.74924179],
       [ 0.10126979],
       [-1.63909341],
       [ 1.89274222],
       [-0.23242587],
       [-0.2073497 ],
       [ 0.95283061],
       [ 0.3595323 ],
       [-1.08718159],
       [-0.72099967],
       [ 1.350306  ],
       [-0.24332625],
       [ 0.56465429],
       [ 0.21745166],
       [ 0.49087183],
       [ 0.72916547],
       [-0.75745323],
       [ 0.50113729],
       [ 0.45181234],
       [ 1.47868574],
       [ 0

In [96]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [97]:
lr.coef_

array([28.16404017])

In [98]:
lr.intercept_

np.float64(-2.7130725669241036)

In [99]:
from sklearn.model_selection import cross_val_score

In [100]:
np.mean(cross_val_score(lr,x,y,scoring="r2",cv=10))

np.float64(0.6375011587464419)

Now i will make my own class by using Gradient descent and that will be same as the SGDREGRESSOR class implemented by Gradient Descent in SKLEARN,That will be amazing

In [180]:
class GDRegressor:
    def __init__(self,learning_rate,epochs):
        self.m=100
        self.b=0
        self.lr=learning_rate
        self.epochs=epochs
    def fit(self,x_train,y_train):
        for i in range(self.epochs):
            step_size_b=-2*(np.sum((y_train-self.m*x_train-self.b)))/len(x_train)
            step_size_m=-2*(np.sum((y_train-self.m*x_train-self.b)*x_train))/len(x_train)
            self.b=self.b-self.lr*step_size_b
            self.m=self.m-self.lr*step_size_m
    def predict(self,x_test):
        return self.m*x_test+self.b

In [181]:
gd=GDRegressor(0.001,9)
gd.fit(x_train,y_train)

In [182]:
res=gd.predict(x_test)

In [183]:
from sklearn.metrics import r2_score
r2_score(y_test,res)

0.6211455799820276

In [184]:
res

array([[ 18.84025316],
       [-22.51663945],
       [ 11.93547059],
       [ 21.19556746],
       [ 28.10813557],
       [ 11.92039985],
       [-26.47507508],
       [ 10.68572364],
       [ 49.34638285],
       [-20.91267662],
       [-44.16528017],
       [ 16.03411154],
       [ 16.85326446],
       [-35.05961412],
       [  6.42068334],
       [  3.56425722],
       [ 11.14960852],
       [-27.91305519],
       [  2.7900151 ],
       [ 17.16609242]])