In [3]:
import numpy as np
import pandas as pd

In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
path=r"C:\Users\deepa\Downloads\covid_toy.csv"

In [7]:
import os

In [8]:
print(os.path.exists(path))

True


In [9]:
df=pd.read_csv(path)

In [10]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [11]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [12]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

from sklearn.model_selection import train_test_split

In [13]:

from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.2)

In [32]:
x_test.shape

(20, 5)

In [16]:
y_train

86    Yes
65     No
99    Yes
51    Yes
62    Yes
     ... 
70     No
63     No
47     No
19    Yes
54    Yes
Name: has_covid, Length: 80, dtype: object

In [17]:
df.sum()

age                                                       4422
gender       MaleMaleMaleFemaleFemaleFemaleMaleFemaleFemale...
fever                                                   9076.0
cough        MildMildMildMildMildMildStrongStrongStrongMild...
city         KolkataDelhiDelhiKolkataMumbaiBangaloreBangalo...
has_covid    NoYesNoNoNoYesNoYesNoNoNoYesNoYesNoYesYesNoYes...
dtype: object

In [18]:
df['city'].isna().sum()

np.int64(0)

In [19]:
si=SimpleImputer(strategy='mean')
x_train_fever=si.fit_transform(x_train[['fever']])
x_test_fever=si.fit_transform(x_test[['fever']])

In [20]:
x_train_fever

array([[104.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [103.        ],
       [104.        ],
       [102.        ],
       [ 99.        ],
       [100.79166667],
       [ 98.        ],
       [100.        ],
       [100.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [100.79166667],
       [102.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [100.79166667],
       [ 98.        ],
       [101.        ],
       [100.79166667],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [100.        ],
       [102.        ],
       [104

In [21]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])
x_test_cough=oe.fit_transform(x_test[['cough']])
x_train_cough

array([[0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [22]:
ohe=OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])
x_train_gender_city

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],


In [27]:
#extracting age
x_train_age=x_train[['age']].values
x_test_age=x_test[['age']].values
x_train_age

array([[25],
       [69],
       [10],
       [11],
       [56],
       [71],
       [83],
       [ 6],
       [64],
       [66],
       [23],
       [40],
       [47],
       [ 5],
       [69],
       [14],
       [80],
       [20],
       [49],
       [19],
       [42],
       [73],
       [34],
       [27],
       [55],
       [34],
       [81],
       [42],
       [34],
       [38],
       [26],
       [15],
       [71],
       [47],
       [46],
       [24],
       [51],
       [12],
       [83],
       [ 8],
       [70],
       [27],
       [33],
       [12],
       [74],
       [19],
       [31],
       [13],
       [38],
       [83],
       [82],
       [60],
       [34],
       [69],
       [23],
       [24],
       [72],
       [64],
       [16],
       [73],
       [44],
       [64],
       [81],
       [54],
       [27],
       [20],
       [65],
       [84],
       [65],
       [50],
       [65],
       [82],
       [80],
       [22],
       [16],
       [68],
       [10],

In [28]:
x_train_age.shape

(80, 1)

In [29]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
x_test_transformed=np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

In [30]:
x_train_transformed

array([[ 25.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 10.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 11.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 83.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [  6.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 64.        , 102.        ,   1.        ,   0.        ,
          0.    

In [39]:
x_train_transf_df

0           1    2    3    4    5    6
0   25.0  104.000000  1.0  0.0  0.0  0.0  0.0
1   69.0  102.000000  0.0  0.0  0.0  0.0  0.0
2   10.0   98.000000  0.0  0.0  1.0  0.0  1.0
3   11.0  100.000000  0.0  0.0  1.0  0.0  1.0
4   56.0  104.000000  0.0  0.0  0.0  0.0  1.0
..   ...         ...  ...  ...  ...  ...  ...
75  68.0  101.000000  0.0  1.0  0.0  0.0  1.0
76  10.0  100.000000  1.0  0.0  0.0  0.0  0.0
77  18.0  104.000000  0.0  0.0  0.0  0.0  0.0
78  42.0  100.791667  0.0  0.0  0.0  0.0  1.0
79  60.0   99.000000  0.0  0.0  0.0  1.0  0.0

[80 rows x 7 columns]

In [40]:
# Here we Use COLUMN TRANSFORMER FOR ALL THESE STUFFS
from sklearn.compose import ColumnTransformer

In [48]:
transformer=ColumnTransformer(
    transformers=[
        ('tnf1',SimpleImputer(strategy='mean'),['fever']),
        ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
        ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])
    ],remainder='passthrough'
)

In [49]:
x_train_ct_df=transformer.fit_transform(x_train)

In [51]:
x_test_ct_df=transformer.fit_transform(x_test)

In [54]:
x_train_ct_df.shape

(80, 7)

In [ ]:
# Here we have done all those stuff in some lines of code 