In [4]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression

In [5]:
X,y=load_diabetes(return_X_y=True)

In [6]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [7]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4526027629719196

In [8]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [9]:
lr.intercept_

np.float64(151.34560453985995)

In [32]:
class MGBD:
    def __init__(self,batch_size,learning_rate,epochs):
        self.coef_=None
        self.intercept_=None
        self.bs=batch_size
        self.lr=learning_rate
        self.epochs=epochs
    def fit(self,x_train,y_train):
        self.coef_=np.ones(x_train.shape[1])
        self.intercept_=0
        for i in range(self.epochs):
            for j in range(int(x_train.shape[0]/self.bs)):
                idx=idx = np.random.choice(x_train.shape[0], self.bs, replace=False)
                y_hat=np.dot(x_train[idx],self.coef_)+self.intercept_
                intercept_dr=-2*np.mean(y_train[idx]-y_hat)
                self.intercept_=self.intercept_ -(self.lr*intercept_dr)
                coef_dr=-2*np.dot((y_train[idx]-y_hat),x_train[idx])
                self.coef_=self.coef_-(self.lr*coef_dr)
    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

In [40]:
mg=MGBD(35,0.01,100)

In [41]:
mg.fit(x_train,y_train)

In [42]:
result=mg.predict(x_test)

In [43]:
result

array([146.49641035, 173.25475595, 145.35165775, 284.26586726,
       129.36201264, 104.22838983, 249.81027092, 195.70625562,
        92.63146915, 120.45772136,  98.7642055 , 148.84019724,
        66.20360589, 210.34622613, 109.72117295, 136.43993642,
       223.9845033 , 245.58536278, 188.7594014 , 212.34769752,
       195.48031593,  92.0412546 ,  79.34966159, 188.48742142,
       152.12759169, 165.160568  , 186.09108563, 174.83095376,
        53.70046251, 122.70973804, 179.33319936,  96.54562764,
       136.33115659, 182.37053808, 174.07225815, 190.30570579,
       130.55784801, 129.02573574, 157.83312176,  63.1336255 ,
        85.63198807, 115.05354288, 156.20368119, 157.40625798,
       171.40287532,  68.25543038,  84.78868526, 104.60971597,
        63.38796217, 151.43238032, 148.29935765,  67.07267945,
       120.35481391, 110.67598064, 172.18459673, 150.85519116,
       102.53190207, 199.4992894 , 114.31280269,  69.94338336,
       183.8465421 , 190.89479188, 141.36550167, 116.01

In [44]:
mg.coef_

array([  40.43689575, -167.26419579,  480.06861732,  301.24244911,
        -48.20493008,  -95.24355282, -209.15500985,  140.2461372 ,
        350.081141  ,  136.42575059])

In [45]:
mg.intercept_

np.float64(151.50524071818924)

In [46]:
r2_score(y_test,result)

0.46049206076764226

Now ,I will use scikit learn 

In [48]:
from sklearn.linear_model import SGDRegressor

In [70]:
sd=SGDRegressor(learning_rate='constant',eta0=0.2)

In [71]:
import random
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(x_train.shape[0]),batch_size)
    sd.partial_fit(x_train[idx],y_train[idx])

In [72]:
sd.coef_

array([  36.3918378 , -181.27961034,  462.30680778,  290.55331886,
        -50.955697  , -102.20330832, -217.34999408,  144.83886976,
        344.73070025,  115.03556002])

In [73]:
sd.intercept_

array([148.75161785])

In [74]:
res=sd.predict(x_test)

In [75]:
r2_score(y_test,res)

0.45708341968849664