In [70]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np

In [71]:
X,y=load_diabetes(return_X_y=True)

In [72]:
y.shape

(442,)

In [73]:
x

array([[-0.71239066],
       [-0.43714566],
       [-0.45375238],
       [ 0.95283061],
       [ 0.23785784],
       [ 0.86121137],
       [-0.24332625],
       [ 0.18494595],
       [-0.72099967],
       [-0.42989708],
       [ 2.01522083],
       [ 0.39724133],
       [ 0.20780005],
       [-0.23242587],
       [-0.76862702],
       [ 0.45315861],
       [ 0.63988397],
       [ 0.3595323 ],
       [-1.61510796],
       [ 1.74924179],
       [-0.78898902],
       [-0.51196509],
       [-0.92833523],
       [ 2.15038297],
       [-0.2073497 ],
       [-1.63909341],
       [-0.33861825],
       [-0.32212366],
       [-0.48137142],
       [-0.52316421],
       [ 0.72196506],
       [ 0.76591105],
       [ 0.45348104],
       [-1.26160595],
       [-2.18711527],
       [-1.18541881],
       [ 0.21745166],
       [ 1.33031692],
       [-1.08718159],
       [ 0.56226171],
       [-1.51284512],
       [-0.00238903],
       [-0.27813452],
       [ 0.45181234],
       [ 1.19070527],
       [ 0

In [74]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [75]:
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [76]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [77]:
lr.intercept_

np.float64(151.34560453985995)

In [78]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4526027629719196

In [79]:
class MySGD:
    def __init__(self,learning_rate,epochs):
        self.coef_=None
        self.intercept_=None
        self.lr=learning_rate
        self.epochs=epochs

    def fit(self,x_train,y_train):
        self.intercept_=0
        self.coef_=np.ones(x_train.shape[1])
        for i in range(self.epochs):
            for i in range(x_train.shape[0]):
                idx=np.random.randint(0,x_train.shape[0])
                y_hat=np.dot(x_train[idx],self.coef_)+self.intercept_
                intercept_dr=-2*(y_train[idx]-y_hat)
                self.intercept_=self.intercept_-(self.lr*intercept_dr)
                coef_dr=-2*np.dot((y_train[idx]-y_hat),x_train[idx])
                self.coef_=self.coef_ - (self.lr*coef_dr)

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

In [98]:
sgd=MySGD(0.01,60)
sgd.fit(x_train,y_train)

In [99]:
res=sgd.predict(x_test)

In [100]:
res

array([144.96474215, 159.73748699, 143.30713128, 267.92739058,
       128.71298214, 104.88413067, 230.51692218, 189.23309994,
        92.05267327, 117.28718604,  95.01548024, 136.33060632,
        59.80007622, 201.40795346, 107.86580456, 127.53357964,
       212.76445337, 232.54459004, 170.57252892, 200.53862932,
       177.1719714 ,  91.72362437,  76.28545643, 179.38942795,
       138.23766473, 157.38296818, 173.58002032, 166.13548397,
        50.49713179, 122.78196476, 167.47899215,  91.60478026,
       131.70229709, 174.70867398, 167.53693549, 177.74163654,
       127.69380615, 128.94143015, 157.58920976,  61.72567065,
        84.7632914 , 112.44635168, 146.81555489, 157.50257493,
       161.68828544,  65.75921397,  79.36530557,  96.46409509,
        61.22267896, 138.20416666, 131.85845115,  63.06482469,
       119.04141705, 105.42379697, 168.19298218, 135.09402042,
       100.86962519, 184.530988  , 105.8352961 ,  64.53536443,
       175.20111792, 173.44952835, 129.56511026, 114.32

In [101]:
r2_score(y_test,res)

0.4333784016094592

In [102]:
sgd.coef_

array([  58.59957907, -118.18779083,  398.84782318,  261.83509179,
        -19.4411724 ,  -61.80025778, -195.91634628,  147.30784287,
        310.10565012,  149.87895683])

In [103]:
sgd.intercept_

np.float64(143.29376697625742)

Now we will scikit learn SGDRegressor class

In [104]:
from sklearn.linear_model import SGDRegressor

In [106]:
sd=SGDRegressor(max_iter=100,learning_rate='constant',eta0=0.01)

In [ ]:
sd.