In [161]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [162]:
# Take a Raw string by using r before the path of the file
path=r"C:\Users\deepa\Downloads\train.csv"

In [163]:
d=pd.read_csv(path)

In [164]:
d.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [165]:
#drops the colums which are of no use
df=d.drop(columns=['PassengerId','Name','Ticket','Cabin'])

In [166]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [167]:
#checks which col have how many missing values
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [168]:
#Does train test split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns='Survived'),df[['Survived']],test_size=0.2,random_state=42)

In [169]:
x_train

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [170]:
x_train['Age']

331    45.5
733    23.0
382    32.0
704    26.0
813     6.0
       ... 
106    21.0
270     NaN
860    41.0
435    14.0
102    21.0
Name: Age, Length: 712, dtype: float64

In [171]:
x_train['Embarked']

331    S
733    S
382    S
704    S
813    S
      ..
106    S
270    S
860    S
435    S
102    S
Name: Embarked, Length: 712, dtype: object

In [172]:
# performed imputation on col having missing vales
si_age=SimpleImputer()
si_ed=SimpleImputer(strategy='most_frequent')
x_train_age=si_age.fit_transform(x_train[['Age']])
x_train_ed=si_ed.fit_transform(x_train[['Embarked']])
x_test_age=si_age.transform(x_test[['Age']])
x_test_ed=si_ed.transform(x_test[['Embarked']])


In [173]:
x_train_ed

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

In [174]:
# OneHotEncoding on Sex and Embarked
ohe_sex=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_ed=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
x_train_sex=ohe_sex.fit_transform(x_train[['Sex']])
x_train_ohe_ed=ohe_ed.fit_transform(x_train_ed)
x_test_sex=ohe_sex.transform(x_test[['Sex']])
x_test_ohe_ed=ohe_ed.transform(x_test_ed)

In [175]:
x_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [176]:
x_train_ohe_ed

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [177]:
# Now I need to CONCATENATE
x_train_rem=x_train.drop(columns=['Sex','Age','Embarked'])
x_test_rem=x_test.drop(columns=['Sex','Age','Embarked'])

# here i will Concatenate

x_train_new=np.concatenate((x_train_rem,x_train_age,x_train_sex,x_train_ohe_ed),axis=1)
x_test_new=np.concatenate((x_test_rem,x_test_age,x_test_sex,x_test_ohe_ed),axis=1)

In [178]:
x_train_new

array([[1., 0., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 2., 0., ..., 0., 0., 1.],
       [1., 1., 2., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.]])

In [179]:
x_test_rem

Pclass  SibSp  Parch     Fare
709       3      1      1  15.2458
439       2      0      0  10.5000
840       3      0      0   7.9250
720       2      0      1  33.0000
39        3      1      0  11.2417
..      ...    ...    ...      ...
433       3      0      0   7.1250
773       3      0      0   7.2250
25        3      1      5  31.3875
84        2      0      0  10.5000
10        3      1      1  16.7000

[179 rows x 4 columns]

In [180]:
# here we have trained our model
clf=DecisionTreeClassifier()
clf.fit(x_train_new,y_train)

DecisionTreeClassifier()

In [181]:
y_pred=clf.predict(x_test_new)

In [182]:
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1])

In [183]:
# Here we calculate the accuracy of our model
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7821229050279329

In [192]:
# for example
row=[1,0,2,41.2345,33,0.,1.,1.,0.,0.]

In [193]:
# created a dataframe using array
y_t1 = pd.DataFrame([row], columns=[
'Pclass','Sibsp','Parch','Fare','Age','Sex',
    'Embarked_1','Embarked_2','Embarked_3','Embarked_4'
])

In [194]:
# It shows 1 means survives
if clf.predict(y_t1)[0]==1:
    print('Survived')
else:
    print('Not Survived')


Not Survived


C:\Users\deepa\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(
