In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes

In [2]:
x,y=load_diabetes(return_X_y=True)

In [3]:
x.shape

(442, 10)

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
ri=Ridge(alpha=0.1,solver='cholesky')

In [7]:
ri.fit(x_train,y_train)

Ridge(alpha=0.1, solver='cholesky')

In [8]:
ri.coef_

array([  42.85566976, -205.49431899,  505.08903304,  317.0932049 ,
       -108.50026183,  -86.23673333, -190.36318008,  151.70708637,
        392.28931896,   79.9081772 ])

In [9]:
ri.intercept_

np.float64(151.45857456679613)

In [10]:
y_pred=ri.predict(x_test)

In [12]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4608521946411924

Let's make our own class

weight=(xTx+lambda*I)^-1(xTy)

In [57]:
class Myreg:
    def __init__(self,alpha):
        self.alpha=alpha
        self.coef_=None
        self.intercept_=None

    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)
        I=np.identity(x_train.shape[1])
        I[0][0]=0
        result=np.linalg.inv(np.dot(x_train.T,x_train)+self.alpha*I).dot(x_train.T).dot(y_train)
        self.coef_=result[1:]
        self.intercept_=result[0]

    def predict(self,x_test):
        return np.dot(x_test,self.coef_[1:]) + self.intercept_

In [58]:
mr=Myreg(0.1)

In [59]:
mr.fit(x_train,y_train)

In [60]:
mr.coef_

array([   0.        ,   42.85566976, -205.49431899,  505.08903304,
        317.0932049 , -108.50026183,  -86.23673333, -190.36318008,
        151.70708637,  392.28931896,   79.9081772 ])

In [61]:
mr.intercept_

np.float64(151.45857456682674)

In [62]:
res=mr.predict(x_test)

In [63]:
res

array([143.86448103, 177.60673096, 143.03578027, 286.63301597,
       125.61640769,  99.75491074, 250.40068384, 189.41436942,
        89.17543131, 115.70368508,  98.53757845, 157.66290287,
        67.5785422 , 205.43931752, 104.35686174, 133.96213954,
       220.15300908, 243.13423921, 191.4543613 , 211.76673001,
       200.99011964,  92.70280503,  77.25581122, 187.3944766 ,
       154.33176476, 163.00948167, 187.22637182, 175.69037816,
        54.57454328, 116.55257444, 178.97163164,  95.3999277 ,
       133.76502749, 180.47075068, 173.08119258, 189.49672058,
       126.27903561, 123.22673789, 150.36862935,  65.10316731,
        81.21214289, 112.0518947 , 159.83741927, 152.73855063,
       173.72838507,  69.7255299 ,  82.98220245, 107.31968241,
        63.66141919, 157.37959813, 153.28244489,  69.12659215,
       118.04187691, 110.52281333, 170.9006869 , 156.3551143 ,
        99.43437595, 202.84270164, 117.87529572,  71.38280493,
       183.68982616, 196.48751431, 141.25634819, 110.68