In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
x,y=load_diabetes(return_X_y=True)

In [5]:
x.shape

(442, 10)

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
x_train.shape

(353, 10)

In [9]:
from sklearn.linear_model import SGDRegressor
sgd=SGDRegressor(max_iter=500,learning_rate='constant',eta0=0.01,alpha=0.0001)


In [10]:
sgd.fit(x_train,y_train)

SGDRegressor(learning_rate='constant', max_iter=500)

In [12]:
sgd.coef_

array([  52.41126334, -130.43664866,  417.2291516 ,  279.82093993,
        -26.63903599,  -70.00489023, -197.19717641,  147.08972741,
        318.20101844,  142.64855034])

In [13]:
sgd.intercept_

array([151.17784457])

In [14]:
res=sgd.predict(x_test)

In [15]:
from sklearn.metrics import r2_score

In [16]:
r2_score(y_test,res)

0.4554525888868435

Now i will scikit learn Ridge class

In [19]:
ri.fit(x_train,y_train)
ri.coef_

array([  37.96896724, -241.90045951,  542.5935044 ,  347.604089  ,
       -919.86392313,  508.99592077,  158.21377539,  273.68991994,
        731.71430609,   48.78692048])

In [20]:
ri.intercept_

np.float64(151.3451787421406)

In [21]:
result=ri.predict(x_test)

In [22]:
r2_score(y_test,result)

0.4526998153190007

In [32]:
class Myridg:

    def __init__(self,learning_rate,epochs,alpha):
        self.coef_=None
        self.intercept_=None
        self.alpha=alpha
        self.lr=learning_rate
        self.epochs=epochs

    def fit(self,x_train,Y_train):
        self.coef_=np.ones(x_train.shape[1])
        self.intercept_=0
        thetha=np.insert(self.coef_,0,self.intercept_)
        for i in range(self.epochs):
            thetha_der = np.dot(x_train.T,x_train).dot(thetha) - np.dot(X_train.T,y_train) + self.alpha*thetha
            thetha = thetha - self.learning_rate*thetha_der
        self.coef_=theta[1:]
        self.intercept_=theta[0]

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

In [33]:
mr=Myridg(0.01,500,0.001)

In [34]:
mr.fit(x_train,y_train)

ValueError: shapes (10,10) and (11,) not aligned: 10 (dim 1) != 11 (dim 0)